// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tuctjtekgyjteevgtgpx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1Y3RqdGVrZ3lqdGVldmd0Z3B4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MDA1MzksImV4cCI6MjA3MzQ3NjUzOX0.T4kYW7IdHvGAIxMxbYbbSFN2YdIyiloy3S76FPV6j3U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});